# Generated by Django 5.0.6 on 2024-06-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_town_cartorder_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon',
            field=models.ManyToManyField(blank=True, related_name='related_coupons', to='store.coupon'),
        ),
    ]
