# Generated by Django 5.0.6 on 2024-06-16 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
